### PR TITLE
Allow adjusting environment variables

### PR DESCRIPTION
**Pull request by fridex**

### CODE REVIEW

**Comment by kennethreitz** [comment]
excellent change

**Comment by kennethreitz** [comment]
released as v0.1.0

**Comment by fridex** [comment]
Excellent response time :+1: Thanks!

**Comment by justinmayer** [comment]
Perhaps consider adding a note to the README so folks know about the new ability to adjust environment variables?

**Comment by kennethreitz** [comment]
pull requests accepted!

**Pull request merged**
