### PR TITLE
Add is_alive() to check for process completion

### PR DESCRIPTION
**Pull request by j00bar**

### CODE REVIEW

**Comment by kennethreitz** [comment]
@j00bar care to rebase?

Sorry for the delay — I didn't have notifications turned on for this repository.

**Comment by blakev** [comment]
If this is still something you want I'd recommend just extracting the function from `psutil` instead of requiring it as a dependency.  It's not too complicated.

See [the source for `pid_exists`](https://github.com/giampaolo/psutil/blob/982f255b4a14c96482ad1ce455b0f2fb0275e144/psutil/_psposix.py#L28-L53).

**Comment by kennethreitz** [comment]
I agree with @blakev

**Comment by kennethreitz** [comment]
https://github.com/kennethreitz/delegator.py/commit/06e44ab0885a3b36a0d380f05927f2017652ed1f

**Comment by kennethreitz** [comment]
thanks, @j00bar!

**Comment by kennethreitz** [comment]
(over a year later, haha!)

**Pull request closed without merging**
